---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mskott/rhocp-demos.git
    targetRevision: main
    path: aap
  destination:
    server: https://kubernetes.default.svc
