namespace: aap # Documentation recommends using "aap"
aap:
  name: aap26 # Name of AnsibleAutomationPlatform resource
  hub:
    fileStorageStorageClass: ocs-external-storagecluster-cephfs
operator:
  channel: stable-2.6

# Using sub-chart helper-status-checker
helper-status-checker:
  enabled: true
  approver: false
  checks:
    - operatorName: ansible-automation-platform
      namespace:
        name: aap
      syncwave: '1'
      serviceAccount:
        name: "aap-status-checker"
